// Code generated by MockGen. DO NOT EDIT.
// Source: blockchain.go

// Package mock is a generated GoMock package.
package mock

import (
	blockchain "github.com/Decentr-net/cerberus/internal/blockchain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBlockchain is a mock of Blockchain interface
type MockBlockchain struct {
	ctrl     *gomock.Controller
	recorder *MockBlockchainMockRecorder
}

// MockBlockchainMockRecorder is the mock recorder for MockBlockchain
type MockBlockchainMockRecorder struct {
	mock *MockBlockchain
}

// NewMockBlockchain creates a new mock instance
func NewMockBlockchain(ctrl *gomock.Controller) *MockBlockchain {
	mock := &MockBlockchain{ctrl: ctrl}
	mock.recorder = &MockBlockchainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBlockchain) EXPECT() *MockBlockchainMockRecorder {
	return m.recorder
}

// DistributeRewards mocks base method
func (m *MockBlockchain) DistributeRewards(rewards []blockchain.Reward) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeRewards", rewards)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistributeRewards indicates an expected call of DistributeRewards
func (mr *MockBlockchainMockRecorder) DistributeRewards(rewards interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeRewards", reflect.TypeOf((*MockBlockchain)(nil).DistributeRewards), rewards)
}
