run:
  concurrency: 4
  deadline: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*

  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Decentr-net
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
  misspell:
    locale: US
  lll:
    line-length: 150
    tab-width: 4
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 1
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    disabled-checks:

    enabled-tags:
      - performance
      - diagnostic

    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32

linters:
  enable-all: true
  fast: false
  disable:
    - wsl
    - gomnd
    - funlen
    - gofumpt
    - testpackage

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - maligned
        - gochecknoglobals
        - lll
        - noctx
        - goerr113

    - path: _mock\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - maligned
        - gochecknoglobals
        - typecheck

    - path: pkg/api/api.go
      linters:
        - gochecknoinits

    - linters:
        - govet
      text: "declaration of \"err\" shadows declaration"

    - linters:
        - lll
      text: "^//( )?go:generate "

    - linters:
        - govet
      source: "log := log"

    - linters:
        - gochecknoglobals
      text: "`log` is a global variable$"

    - linters:
        - staticcheck
      source: "choice:\".+\""

  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  new: false
