version: '2.2'

networks:
  decentr-cerberus:
    name: decentr-cerberus
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.231.0/24
          gateway: 172.16.231.1

services:
  cerberus:
    # use this image for local image
    # image: cerberus-local:latest
    image: decentr:cerberus
    container_name: decentr-cerberus
    restart: always
    environment:
      - "HTTP_HOST=0.0.0.0"
      - "HTTP_PORT=7070"
      - "S3_ENDPOINT=s3:9000"
      - "S3_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"
      - "S3_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      - "S3_USE_SSL=false"
      - "S3_BUCKET=cerberus"
      - "ENCRYPT_KEY=0102030405060708090a0b0c0d0e0f10201f1e1d1c1b1a191817161514131211"
      - "LOG_LEVEL=debug"
    networks:
      - decentr-cerberus
    ports:
      - "7070:7070"
    depends_on:
      - s3

  s3:
    image: minio/minio:latest
    container_name: decentr-s3
    restart: always
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: ["minio","server","/data"]
    networks:
      - decentr-cerberus
    ports:
      - "9000:9000"
